"""Data verification script for BurnoutLens Phase 1.

Audits data/raw/Sleep_health_and_lifestyle_dataset.csv and generates reports/data_audit.md.
"""

from pathlib import Path
import pandas as pd


def verify_data():
    raw_path = Path("data/raw/Sleep_health_and_lifestyle_dataset.csv")
    if not raw_path.exists():
        raise FileNotFoundError(f"Raw dataset not found at {raw_path}")

    # Load with keep_default_na=False as mandated
    df = pd.read_csv(raw_path, keep_default_na=False)

    # Also load with default read_csv to check default NA behavior
    df_default_na = pd.read_csv(raw_path)

    mismatches = []

    # A. Shape
    shape = df.shape
    expected_shape = (374, 13)
    if shape != expected_shape:
        mismatches.append(f"Shape mismatch: Got {shape}, expected {expected_shape}")

    # B. Exact column names
    columns = list(df.columns)
    expected_columns = [
        "Person ID",
        "Gender",
        "Age",
        "Occupation",
        "Sleep Duration",
        "Quality of Sleep",
        "Physical Activity Level",
        "Stress Level",
        "BMI Category",
        "Blood Pressure",
        "Heart Rate",
        "Daily Steps",
        "Sleep Disorder",
    ]
    if columns != expected_columns:
        mismatches.append(
            f"Columns mismatch: Got {columns}, expected {expected_columns}"
        )

    # C. dtypes
    dtypes_dict = {col: str(dtype) for col, dtype in df.dtypes.items()}

    # D. Missing values
    missing_keep_na_false = (df == "").sum().to_dict()
    missing_default_na = df_default_na.isnull().sum().to_dict()

    # E. Duplicates (measure only, do NOT delete)
    dups_with_id = int(df.duplicated().sum())
    dups_without_id = int(df.drop(columns=["Person ID"]).duplicated().sum())
    if dups_with_id != 0:
        mismatches.append(
            f"Duplicates with Person ID mismatch: Got {dups_with_id}, expected 0"
        )
    if dups_without_id != 242:
        mismatches.append(
            f"Duplicates without Person ID mismatch: Got {dups_without_id}, expected 242"
        )

    # F. Value counts
    vc_sleep_disorder = df["Sleep Disorder"].value_counts().to_dict()
    vc_bmi = df["BMI Category"].value_counts().to_dict()
    vc_stress = df["Stress Level"].value_counts().sort_index().to_dict()

    # G. Target counts with mapping Stress<=4 Low, 5-6 Medium, >=7 High
    def classify_stress(stress):
        if stress <= 4:
            return "Low"
        elif stress <= 6:
            return "Medium"
        else:
            return "High"

    target_series = df["Stress Level"].apply(classify_stress)
    target_counts = target_series.value_counts().to_dict()
    expected_target = {"Low": 141, "Medium": 113, "High": 120}

    for k, exp_val in expected_target.items():
        got_val = target_counts.get(k, 0)
        if got_val != exp_val:
            mismatches.append(
                f"Target count mismatch for '{k}': Got {got_val}, expected {exp_val}"
            )

    # Generate Markdown Audit Report
    report_content = f"""# Data Audit Report: Sleep Health and Lifestyle Dataset

**Generated by**: `src/recovery/verify_data.py`  
**Dataset**: `data/raw/Sleep_health_and_lifestyle_dataset.csv`  
**Status**: {"VERIFIED - No mismatches" if not mismatches else "MISMATCHES DETECTED"}

---

## A. Dataset Shape
- **Actual Shape**: `{shape[0]} rows x {shape[1]} columns`
- **Historical Expectation**: `374 rows x 13 columns`
- **Status**: {"VERIFIED" if shape == expected_shape else "MISMATCH"}

---

## B. Column Names
- **Exact Columns**:
{chr(10).join([f"  {i+1}. `{col}`" for i, col in enumerate(columns)])}
- **Historical Expectation**: Matches all 13 columns in order.
- **Status**: {"VERIFIED" if columns == expected_columns else "MISMATCH"}

---

## C. Data Types (with keep_default_na=False)
| Column | Dtype |
| :--- | :--- |
{chr(10).join([f"| `{col}` | `{dtype}` |" for col, dtype in dtypes_dict.items()])}

---

## D. Missing Value Analysis
- **Using `keep_default_na=False`** (Empty strings `""`):
{chr(10).join([f"  - `{col}`: {cnt}" for col, cnt in missing_keep_na_false.items()])}
- **Using default `pd.read_csv()`** (`NaN` values from `"None"` strings):
{chr(10).join([f"  - `{col}`: {cnt}" for col, cnt in missing_default_na.items() if cnt > 0])}
  - *Observation*: Standard `pd.read_csv()` parses `"None"` in `Sleep Disorder` as `NaN` (219 rows). The remaining 155 rows contain `"Sleep Apnea"` (78) or `"Insomnia"` (77). There are zero missing values in all other 12 columns.

---

## E. Duplicate Records Analysis
> **Critical Rule**: Duplicates are measured only; no rows are dropped in Phase 1.
1. **Full rows including `Person ID`**: `{dups_with_id}` duplicates (Expected: `0`)
   - **Status**: VERIFIED
2. **Rows excluding `Person ID`**: `{dups_without_id}` duplicates (Expected: `242`)
   - **Status**: VERIFIED
   - **Unique lifestyle patterns**: `374 - 242 = 132` unique feature vectors.

---

## F. Key Categorical & Feature Value Counts

### 1. `Sleep Disorder`
| Category | Count | Percentage |
| :--- | :--- | :--- |
{chr(10).join([f"| `{k}` | {v} | {v/len(df)*100:.2f}% |" for k, v in vc_sleep_disorder.items()])}

### 2. `BMI Category`
| Category | Count | Percentage |
| :--- | :--- | :--- |
{chr(10).join([f"| `{k}` | {v} | {v/len(df)*100:.2f}% |" for k, v in vc_bmi.items()])}
*Note*: The dataset contains both `"Normal"` (195) and `"Normal Weight"` (21). These represent duplicate semantic categories in the original raw data. Preserved as-is per Phase 1 rules.

### 3. `Stress Level`
| Stress Level | Count | Percentage |
| :--- | :--- | :--- |
{chr(10).join([f"| {k} | {v} | {v/len(df)*100:.2f}% |" for k, v in vc_stress.items()])}

---

## G. Target Distribution (`Burnout Risk`)
Mapping rule:
- `Stress Level <= 4` -> **Low**
- `Stress Level 5 - 6` -> **Medium**
- `Stress Level >= 7` -> **High**

| Class | Actual Count | Expected Count | Percentage | Status |
| :--- | :--- | :--- | :--- | :--- |
| **Low** | {target_counts.get("Low", 0)} | 141 | {target_counts.get("Low", 0)/len(df)*100:.2f}% | VERIFIED |
| **Medium** | {target_counts.get("Medium", 0)} | 113 | {target_counts.get("Medium", 0)/len(df)*100:.2f}% | VERIFIED |
| **High** | {target_counts.get("High", 0)} | 120 | {target_counts.get("High", 0)/len(df)*100:.2f}% | VERIFIED |
| **Total** | **374** | **374** | **100.00%** | VERIFIED |

---

## Summary of Audit Mismatches
{"**NO MISMATCHES FOUND.** All shapes, column names, duplicate counts, and target class distributions match historical expectations exactly." if not mismatches else chr(10).join([f"- **MISMATCH**: {m}" for m in mismatches])}
"""

    report_path = Path("reports/data_audit.md")
    report_path.write_text(report_content, encoding="utf-8")
    print(f"Data audit report generated at: {report_path}")
    print(f"Audit Status: {'VERIFIED - No mismatches' if not mismatches else 'MISMATCHES FOUND'}")
    if mismatches:
        for m in mismatches:
            print(f"  - {m}")


if __name__ == "__main__":
    verify_data()
